"""
CRUD operations for the Notification model.

This module provides decoupled functions to create, retrieve, update, and manage
the exact state of outbound notifications (e.g., Telegram messages or JSON files)
sent by the automation engine to the user.
"""

from datetime import datetime, timezone
from sqlalchemy import select
from sqlalchemy.orm import Session
from src.app.core.enums import NotificationStatus
from src.app.models.notification import Notification
from src.app.schemas.notification import NotificationCreate, NotificationUpdate


def create_notification(
    db: Session, notification_data: NotificationCreate
) -> Notification:
    """
    Create a new notification log entry before a delivery attempt starts.
    The status defaults to PENDING.

    Args:
        db (Session): The active database session.
        notification_data (NotificationCreate): Validated data for the new notification.

    Returns:
        Notification: The newly created Notification ORM object.
    """
    notification = Notification(
        search_run_id=notification_data.search_run_id,
        channel=notification_data.channel,
        message=notification_data.message,
        jobs_sent=notification_data.jobs_sent,
        file_path=notification_data.file_path,
    )

    db.add(notification)
    db.flush()

    return notification


def get_notification_by_id(db: Session, notification_id: int) -> Notification | None:
    """
    Retrieve a specific notification record by its primary key ID.

    Args:
        db (Session): The active database session.
        notification_id (int): The ID of the notification.

    Returns:
        Notification | None: The Notification object if found, otherwise None.
    """
    stmt = select(Notification).where(Notification.id == notification_id)
    return db.scalar(stmt)


def get_notifications_by_search_run(
    db: Session, search_run_id: int
) -> list[Notification]:
    """
    Retrieve all notifications generated by a specific search run execution.

    Args:
        db (Session): The active database session.
        search_run_id (int): The ID of the search run.

    Returns:
        list[Notification]: A list of Notification objects, ordered newest first.
    """
    stmt = (
        select(Notification)
        .where(Notification.search_run_id == search_run_id)
        .order_by(Notification.created_at.desc())
    )

    return list(db.scalars(stmt).all())


def update_notification(
    db: Session,
    notification: Notification,
    notification_data: NotificationUpdate,
) -> Notification:
    """
    Dynamically update an existing notification's details.

    Args:
        db (Session): The active database session.
        notification (Notification): The existing Notification object to update.
        notification_data (NotificationUpdate): Validated schema with fields to update.

    Returns:
        Notification: The updated Notification object.
    """
    update_data = notification_data.model_dump(exclude_unset=True)

    for key, value in update_data.items():
        setattr(notification, key, value)

    db.flush()

    return notification


def mark_notification_as_sent(
    db: Session,
    notification: Notification,
    message: str | None = None,
) -> Notification:
    """
    Mark a notification as successfully sent and record the exact UTC dispatch time.

    Args:
        db (Session): The active database session.
        notification (Notification): The Notification object to update.
        message (str | None): Optional final text or summary that was actually sent.

    Returns:
        Notification: The updated Notification object.
    """
    notification.status = NotificationStatus.SENT
    notification.sent_at = datetime.now(timezone.utc)

    if message is not None:
        notification.message = message

    db.flush()

    return notification


def mark_notification_as_failed(
    db: Session,
    notification: Notification,
    error_details: str,
    message: str | None = None,
) -> Notification:
    """
    Mark a notification as failed and permanently log the exception details.
    Crucial for identifying issues like Telegram API blocks or invalid Chat IDs.

    Args:
        db (Session): The active database session.
        notification (Notification): The Notification object to update.
        error_details (str): The specific exception message or API error reason.
        message (str | None): Optional context about the payload.

    Returns:
        Notification: The updated Notification object.
    """
    notification.status = NotificationStatus.FAILED
    notification.error_details = error_details

    if message is not None:
        notification.message = message

    db.flush()

    return notification


def delete_notification(db: Session, notification: Notification) -> None:
    """
    Permanently delete a notification record from the database.

    Args:
        db (Session): The active database session.
        notification (Notification): The Notification object to delete.
    """
    db.delete(notification)
    db.flush()
